spring.application.name=library

spring.datasource.url = jdbc:mysql://localhost:3306/lib
spring.datasource.username = root
spring.datasource.password = X1AL191981
spring.jpa.hibernate.ddl-auto = validate
